---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: myip
    app.kubernetes.io/part-of: myip
    app.kubernetes.io/version: "1.0.0"
  name: myip
spec:
  finalizers:
    - kubernetes
