---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: myip
    app.kubernetes.io/part-of: myip
    app.kubernetes.io/version: "1.0.0"
  name: myip
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myip-data
  labels:
    app.kubernetes.io/part-of: myip
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: myip
  labels:
    app.kubernetes.io/name: myip
    app.kubernetes.io/version: "1.0.0"
spec:
  schedule: "0 */2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: myip
              image: ivaquero/myip:1.0.0
              env:
                - name: ROUTE53_MYIP_FILE_PATH
                  value: /data/ip.txt
                - name: ROUTE53_MYIP_NAME
                  value: ${ROUTE53_MYIP_NAME:=home.ignaciovaquero.es}
              envFrom:
                - secretRef:
                    name: myip-aws-credentials
              resources:
                requests:
                  cpu: 100m
                  memory: 16Mi
                limits:
                  cpu: 200m
                  memory: 64Mi
              volumeMounts:
                - mountPath: /data
                  name: ${ROUTE53_MYIP_VOLUME:=myip-data}
          restartPolicy: OnFailure
          volumes:
            - name: ${ROUTE53_MYIP_VOLUME:=myip-data}
              persistentVolumeClaim:
                claimName: ${ROUTE53_MYIP_VOLUME:=myip-data}
