---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: myip
  labels:
    app.kubernetes.io/name: myip
    app.kubernetes.io/version: "1.0.0"
spec:
  schedule: "0 */2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: myip
              image: ivaquero/myip:1.0.0
              env:
                - name: ROUTE53_MYIP_FILE_PATH
                  value: /data/ip.txt
                - name: ROUTE53_MYIP_NAME
                  value: home.ignaciovaquero.es
              envFrom:
                - secretRef:
                    name: myip-aws-credentials
              resources:
                requests:
                  cpu: 100m
                  memory: 16Mi
                limits:
                  cpu: 200m
                  memory: 64Mi
              volumeMounts:
                - mountPath: /data
                  name: myip-data
          restartPolicy: OnFailure
          volumes:
            - name: myip-data
              persistentVolumeClaim:
                claimName: myip-data
