---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myip-data
  labels:
    app.kubernetes.io/part-of: myip
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi
